// Custom Worker entry point.
// Reuses the OpenNext-generated `fetch` handler and adds a `scheduled`
// handler that warms the KV cache via /api/cron/refresh.
// On Workers Free, user requests cannot afford to refresh the AA scrape
// themselves (10 ms CPU limit), so the cron triggers do it ahead of time.

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — `.open-next/worker.js` is generated by @opennextjs/cloudflare at build time
import { default as openNextHandler } from "./.open-next/worker.js";

interface CronEnv {
  WORKER_SELF_REFERENCE?: Service;
  CRON_SECRET?: string;
}

export default {
  fetch: openNextHandler.fetch,

  async scheduled(_event: ScheduledController, env: CronEnv, ctx: ExecutionContext) {
    if (!env.WORKER_SELF_REFERENCE) {
      console.error("scheduled: WORKER_SELF_REFERENCE binding missing");
      return;
    }
    if (!env.CRON_SECRET) {
      console.error("scheduled: CRON_SECRET secret missing");
      return;
    }

    const refresh = env.WORKER_SELF_REFERENCE.fetch(
      "https://internal/api/cron/refresh",
      {
        method: "POST",
        headers: { authorization: `Bearer ${env.CRON_SECRET}` },
      },
    ).then(async (res) => {
      const body = await res.text();
      if (!res.ok) {
        console.error(`scheduled: refresh failed ${res.status} ${body}`);
      } else {
        console.log(`scheduled: refresh ok ${body}`);
      }
    });

    ctx.waitUntil(refresh);
  },
} satisfies ExportedHandler<CronEnv>;
