// Custom Worker entry point.
// - Reuses the OpenNext-generated `fetch` handler for user requests.
// - Adds a `scheduled` handler that warms the KV cache *directly* (not via
//   self-reference HTTP), so the cron benefits from its own 15-min CPU
//   budget instead of being capped by `limits.cpu_ms` from wrangler.jsonc.

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — `.open-next/worker.js` is generated by @opennextjs/cloudflare at build time
import { default as openNextHandler } from "./.open-next/worker.js";
import { refreshKVCache } from "./lib/cron-refresh";

export default {
  fetch: openNextHandler.fetch,

  async scheduled(_event: ScheduledController, env: CloudflareEnv, ctx: ExecutionContext) {
    ctx.waitUntil(
      refreshKVCache(env)
        .then((r) => console.log(`cron: refreshed ${r.count} models in ${r.durationMs}ms`))
        .catch((e) => console.error("cron: refresh failed:", e)),
    );
  },
} satisfies ExportedHandler<CloudflareEnv>;
