blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/scorpion7slayer/nxtaicard/discussions
    about: Pour les questions générales, utilise les Discussions GitHub.
